name: PlatformIO CI
on: 
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: ["."]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: pio run
        run: pio run
      - name: Build PlatformIO 
        run: pio ci --project-option="lib_tdf_mode=chain+" --lib="./lib/*" --keep-build-dir --project-conf=./platformio.ini --build-dir="$HOME" .
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}